---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: quota-limit-cluster-role
    rules:
      - apiGroups:
          - ""
        resources:
          - limitranges
          - resourcequotas
        verbs:
          - create
          - delete
          - patch
          - update
          - get
          - list
          - watch
      - apiGroups:
          - networking.k8s.io
        resources:
          - networkpolicies
        verbs:
          - create
          - delete
          - patch
          - update
          - get
          - list
          - watch
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: openshift-gitops-manage-quota-limit
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: quota-limit-cluster-role
    subjects:
      - kind: ServiceAccount
        name: openshift-gitops-argocd-application-controller
        namespace: openshift-gitops
