---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: project.openshift.io/v1
    kind: Project
    metadata:
      name: query-logs
  - apiVersion: v1
    kind: PersistentVolumeClaim
    metadata:
      labels:
        app: mariadb
      name: mariadb
      namespace: query-logs
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: mariadb
      name: mariadb
      namespace: query-logs
    stringData:
      database-name: cs220db
      database-password: redhat
      database-root-password: redhat
      database-user: operator1
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: mariadb
        tier: database
      name: mariadb
      namespace: query-logs
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: mariadb
      strategy:
        type: Recreate
      template:
        metadata:
          labels:
            app: mariadb
            tier: database
        spec:
          volumes:
            - name: mariadb-data
              persistentVolumeClaim:
                claimName: mariadb
          containers:
            - name: mariadb
              image: registry.redhat.io/rhel9/mariadb-105
              volumeMounts:
                - mountPath: /var/lib/mysql/data
                  name: mariadb-data
              ports:
                - containerPort: 3306
              env:
                - name: MYSQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: mariadb
                - name: MYSQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: mariadb
                - name: MYSQL_ROOT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-root-password
                      name: mariadb
                - name: MYSQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: mariadb
              livenessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
                initialDelaySeconds: 30
                timeoutSeconds: 1
              readinessProbe:
                exec:
                  command:
                    - /bin/sh
                    - -i
                    - -c
                    - MYSQL_PWD="$MYSQL_PASSWORD" mysqladmin -u $MYSQL_USER ping
                initialDelaySeconds: 5
                timeoutSeconds: 1
              resources:
                limits:
                  memory: 512Mi
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: mariadb
      name: mariadb
      namespace: query-logs
    spec:
      ports:
        - name: mariadb
          port: 3306
      selector:
        app: mariadb

  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: famous-quotes
        tier: front
      name: famous-quotes
      namespace: query-logs
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: famous-quotes
      template:
        metadata:
          labels:
            app: famous-quotes
            tier: front
        spec:
          containers:
            - name: famous-quotes
              # Wrong image (tag must be 2.1)
              image: quay.io/redhattraining/famous-quotes:CHANGE_ME
              ports:
                - containerPort: 8000
                  protocol: TCP
              env:
                - name: QUOTES_HOSTNAME
                  value: mariadb
                - name: QUOTES_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: mariadb
                - name: QUOTES_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: mariadb
                - name: QUOTES_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: mariadb
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: famous-quotes
      name: famous-quotes
      namespace: query-logs
    spec:
      ports:
        - protocol: TCP
          port: 8000
          targetPort: 8000
      selector:
        app: famous-quotes
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: famous-quotes
      name: famous-quotes
      namespace: query-logs
    spec:
      port:
        targetPort: 8000
      to:
        kind: Service
        name: famous-quotes
      tls:
        termination: edge
  # Unschedulable (needs too much memory)
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: need-20gib
      name: need-20gib
      namespace: query-logs
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: need-20gib
      template:
        metadata:
          labels:
            app: need-20gib
        spec:
          containers:
            - name: need-20gib
              image: quay.io/redhattraining/long-load:v1
              resources:
                requests:
                  memory: 20Gi
              ports:
                - containerPort: 3000
              readinessProbe:
                initialDelaySeconds: 10
                httpGet:
                  path: /health
                  port: 3000
              livenessProbe:
                initialDelaySeconds: 30
                httpGet:
                  path: /health
                  port: 3000
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
