---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: hello-world
      name: hello-world
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: hello-world
      template:
        metadata:
          labels:
            app: hello-world
        spec:
          initContainers:
            - name: pull-s3-data
              image: registry.access.redhat.com/ubi9/ubi:latest
              env:
                - name: URL
                  value: <CHANGE_ME>
              command:
                - sh
                - -c
                - "curl -o /tmp/dest/index.html ${URL}/data.txt
                  && chmod 444 /tmp/dest/index.html"
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
              volumeMounts:
                - name: config-emptydir
                  mountPath: /tmp/dest
          containers:
            - name: hello-world
              image: registry.access.redhat.com/ubi9/httpd-24:1
              resources:
                requests:
                  memory: 500Mi
              ports:
                - containerPort: 8080
              readinessProbe:
                initialDelaySeconds: 5
                httpGet:
                  path: /
                  port: 8080
              livenessProbe:
                initialDelaySeconds: 15
                httpGet:
                  path: /
                  port: 8080
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
              volumeMounts:
                - name: config-emptydir
                  mountPath: /var/www/html
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
          volumes:
            - name: config-emptydir
              emptyDir: {}
  - apiVersion: v1
    kind: Service
    metadata:
      labels:
        app: hello-world
      name: hello-world
    spec:
      ports:
        - protocol: TCP
          port: 8080
          targetPort: 8080
      selector:
        app: hello-world
  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      labels:
        app: hello-world
      name: hello-world
    spec:
      tls:
        termination: edge
      to:
        kind: Service
        name: hello-world
