---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cert-pub
  namespace: openshift-ingress
spec:
  secretName: cert-pub-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: "*.apps.<CHANGE_ME>"
  dnsNames:
    - "*.apps.<CHANGE_ME>"
