---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: Secret
    metadata:
      labels:
        app: sqs-send
      name: sqs-send
    stringData:
      queue-name: <CHANGE_ME>
      region: <CHANGE_ME>
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: sqs-send
      name: sqs-send
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: sqs-send
      template:
        metadata:
          labels:
            app: sqs-send
        spec:
          containers:
            - name: sqs-send
              image: quay.io/redhattraining/cs22x-sqs-send:v1.0
              env:
                - name: AWS_SQS_QUEUE_NAME
                  valueFrom:
                    secretKeyRef:
                      key: queue-name
                      name: sqs-send
                - name: AWS_DEFAULT_REGION
                  valueFrom:
                    secretKeyRef:
                      key: region
                      name: sqs-send
              resources:
                requests:
                  memory: 100Mi
              securityContext:
                capabilities:
                  drop:
                    - ALL
                allowPrivilegeEscalation: false
              imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
