---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <CHANGE_ME>
    privateKeySecretRef:
      name: letsencrypt-staging-issuer-account-key
    solvers:
      - dns01:
          route53:
            hostedZoneID: <CHANGE_ME>
            region: <CHANGE_ME>
