{{- range $index, $value := .Values.allowedNamespaceLabels }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-{{ $index }}
  namespace: {{ $.Values.namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              {{ $value.name }}: {{ $value.value | quote }}
{{- end }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-local
  namespace: {{ .Values.namespace }}
spec:
  podSelector: {}
  ingress:
    - from:
      - podSelector: {}
