{{- range .Values.groups }}
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .name }}-{{ .role }}
  namespace: {{ $.Values.namespace }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .role }}
{{- end }}
