---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.groupName }}-edit
  namespace: {{ .Values.namespace }}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: {{ .Values.groupName }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: edit
