---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: etherpad-st1
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
parameters:
  csi.storage.k8s.io/fstype: ext4
  type: st1
  encrypted: "true"
