---
apiVersion: v1
kind: List
metadata: {}
items:
  - apiVersion: v1
    kind: ResourceQuota
    metadata:
      name: quota
    spec:
      hard:
        pods: "4"
        requests.cpu: "1"
        requests.memory: 4Gi
        limits.cpu: "2"
        limits.memory: 8Gi

  - apiVersion: v1
    kind: LimitRange
    metadata:
      name: limit-range
    spec:
      limits:
        - defaultRequest:
            cpu: 100m
            memory: 256Mi
          default:
            cpu: 200m
            memory: 512Mi
          type: Container

  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-local
    spec:
      podSelector: {}
      ingress:
        - from:
            - podSelector: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-ingress
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  policy-group.network.openshift.io/ingress: ""
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: allow-monitoring
    spec:
      podSelector: {}
      ingress:
        - from:
            - namespaceSelector:
                matchLabels:
                  network.openshift.io/policy-group: monitoring
