---
AWSTemplateFormatVersion: "2010-09-09"
Description: >
  This template creates an AWS Cognito resources for the guided exercise.

Parameters:
  RosaStackName:
    Description: >
      Name of the stack that deployed the AWS Cognito Resources
    Type: String
  # pCognitoUserPoolUserAmelia:
  #   Username: amroy
  #   UserAttributes:
  #     name: Amelia Roy
  #     email: amroy@cs220cluster
  #     email_verified: true
  #   Type: String

Resources:
  # Cognito user-pool
  rCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: cs220-user-pool
      AutoVerifiedAttributes:
        - email
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
  # Create user-pool Domain
  rCognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    DependsOn: rCognitoUserPool
    Properties:
      Domain: cs220-cluster
      UserPoolId:
        Ref: rCognitoUserPool
  # Create users for Cognito
  rCognitoUserPoolUserAmelia:
    Type: AWS::Cognito::UserPoolUser
    DependsOn: rCognitoUserPool
    Properties:
      Username: amroy
      UserAttributes:
        - Name: name
          Value: Amelia Roy
        - Name: email
          Value: amroy@cs220cluster
        - Name: email_verified
          Value: true
      UserPoolId:
        Ref: rCognitoUserPool
  rCognitoUserPoolUserSue:
    Type: AWS::Cognito::UserPoolUser
    DependsOn: rCognitoUserPool
    Properties:
      Username: smoody
      UserAttributes:
        - Name: name
          Value: Sue Moody
        - Name: email
          Value: smoody@cs220cluster
        - Name: email_verified
          Value: true
      UserPoolId:
        Ref: rCognitoUserPool
  rCognitoUserPoolUserRoberto:
    Type: AWS::Cognito::UserPoolUser
    DependsOn: rCognitoUserPool
    Properties:
      Username: rruiz
      UserAttributes:
        - Name: name
          Value: Roberto Ruiz
        - Name: email
          Value: rruiz@cs220cluster
        - Name: email_verified
          Value: true
      UserPoolId:
        Ref: rCognitoUserPool
  rCongnitoUserPoolGroupManagers:
    Type: AWS::Cognito::UserPoolGroup
    DependsOn: rCognitoUserPool
    Properties:
      GroupName: managers
      Description: >
        Group for Managers
      UserPoolId:
        Ref: rCognitoUserPool
  rCongnitoUserPoolGroupDevelopers:
    Type: AWS::Cognito::UserPoolGroup
    DependsOn: rCognitoUserPool
    Properties:
      GroupName: developers
      Description: >
        Group for Developers
      UserPoolId:
        Ref: rCognitoUserPool
  rCongnitoUserPoolGroupOperations:
    Type: AWS::Cognito::UserPoolGroup
    DependsOn: rCognitoUserPool
    Properties:
      GroupName: operations
      Description: >
        Group for Operations
      UserPoolId:
        Ref: rCognitoUserPool
